### Post informes
POST http://localhost:4000/api/informes
Content-Type: application/json

{ 
    "latitud": "-34.55217",
    "longitud": "-58.69784",
    "label_1": "label_1",
    "conf_1": "conf_1",
    "label_2": "label_2",
    "conf_2": "conf_2"
}


### LIsting
GET http://localhost:4000/api/informes
Content-Type: application/json